import AttendeeStatusEnum from "./AttendeeStatusEnum";
import { MetaValue } from "./MetaValueModel";

export type Attendee = {
  id: string;
  meetId: string;
  userId?: string;
  status: AttendeeStatusEnum;
  sequence: number;
  respondedAt: string;
  notifiedAt?: string;
  name: string;
  phone?: string;
  email?: string;
  guests: number;
  guestOf?: string;
  isMinor?: boolean;
  guardianName?: string;
  indemnityAccepted: boolean;
  indemnityMinors?: string;
  indemnityAcceptance?: {
    acceptedAt?: string;
    confirmedAt?: string;
    confirmationMethod?: "email" | "sign-in" | string;
    indemnityTextHash?: string;
    acceptanceIp?: string;
    acceptanceUserAgent?: string;
    acceptedByName?: string;
    acceptedByEmail?: string;
    acceptedByPhone?: string;
    locale?: string;
    timeZone?: string;
  };
  paidFullAt?: string;
  paidDepositAt?: string;
  hasUnreadMessages: boolean;
  createdAt: string;
  updatedAt: string;
  metaValues: Array<MetaValue>;
};
