export type Meet = {
  id: string;
  name: string;
  organizerId: string;
  description?: string | null;
  organizationId?: string | null;
  location?: string | null;
  locationLat?: number | null;
  locationLong?: number | null;
  startTime?: string | null;
  endTime?: string | null;
  startTimeTbc?: boolean | null;
  endTimeTbc?: boolean | null;
  useMap?: boolean | null;
  openingDate?: string | null;
  closingDate?: string | null;
  scheduledDate?: string | null;
  confirmDate?: string | null;
  status?: string;
  statusId?: number | null;
  organizerName?: string | null;
  organizerFirstName?: string | null;
  organizerLastName?: string | null;
  organizerEmail?: string | null;
  organizerPhone?: string | null;
  imageUrl?: string | null;
  capacity?: number | null;
  waitlistSize?: number | null;
  autoPlacement?: boolean | null;
  autoPromoteWaitlist?: boolean | null;
  allowGuests?: boolean | null;
  maxGuests?: number | null;
  isVirtual?: boolean | null;
  shareCode?: string | null;
  currency?: string | null;
  currencyId?: number | null;
  currencySymbol?: string | null;
  costCents?: number | null;
  depositCents?: number | null;
  waitlistMessage?: string | null;
  confirmMessage?: string | null;
  rejectMessage?: string | null;
  hasIndemnity?: boolean | null;
  indemnity?: string | null;
  allowMinorIndemnity?: boolean | null;
  attendeeCount?: number | null;
  waitlistCount?: number | null;
  confirmedCount?: number | null;
  checkedInCount?: number | null;
  isHidden?: boolean | null;
  myAttendeeStatus?: string | null;
  metaDefinitions?: Array<{
    id: string;
    fieldKey: string;
    label: string;
    fieldType: string;
    required?: boolean | null;
    position?: number | null;
    config?: Record<string, any> | null;
  }> | null;
};

export default Meet;
