export type Meet = {
  id: string;
  name: string;
  organizerId: string;
  description?: string;
  organizationId?: string;
  location?: string;
  locationLat?: number;
  locationLong?: number;
  startTime?: string | Date;
  endTime?: string | Date;
  startTimeTbc?: boolean;
  endTimeTbc?: boolean;
  useMap?: boolean;
  openingDate?: string | Date;
  closingDate?: string | Date;
  scheduledDate?: string | Date;
  confirmDate?: string | Date;
  status?: string;
  statusId?: number;
  organizerName?: string;
  organizerFirstName?: string;
  organizerLastName?: string;
  organizerEmail?: string;
  organizerPhone?: string;
  imageUrl?: string;
  images?: Array<{
    id: string;
    meetId: string;
    url: string;
    isPrimary: boolean;
    aspect: "W" | "S" | "P" | "O";
    objectKey?: string;
    contentType?: string;
    sizeBytes?: number;
    createdAt?: string;
  }>;
  capacity?: number;
  waitlistSize?: number;
  autoPlacement?: boolean;
  autoPromoteWaitlist?: boolean;
  allowGuests?: boolean;
  allowSelfCheckin?: boolean;
  allowWalkins?: boolean;
  maxGuests?: number;
  isVirtual?: boolean;
  shareCode?: string;
  currency?: string;
  currencyId?: number;
  currencySymbol?: string;
  costCents?: number;
  depositCents?: number;
  waitlistMessage?: string;
  confirmMessage?: string;
  rejectMessage?: string;
  hasIndemnity?: boolean;
  indemnity?: string;
  allowMinorIndemnity?: boolean;
  attendeeCount?: number;
  waitlistCount?: number;
  confirmedCount?: number;
  checkedInCount?: number;
  isHidden?: boolean;
  myAttendeeStatus?: string;
  metaDefinitions?: Array<{
    id: string;
    fieldKey: string;
    label: string;
    fieldType: string;
    required?: boolean;
    position?: number;
    config?: Record<string, any>;
  }>;
};

export default Meet;
