export type Meet = {
  id: string;
  name: string;
  description?: string;
  location?: string;
  startTime?: string;
  endTime?: string;
  openingDate?: string;
  status?: string;
  organizerId?: string;
  organizerName?: string;
  organizerEmail?: string;
  organizerPhone?: string;
  imageUrl?: string;
  capacity?: number;
  waitlistSize?: number;
  allowGuests?: boolean;
  maxGuests?: number;
  shareCode?: string;
  currency?: string;
  currencySymbol?: string;
  costCents?: number | null;
  waitlistMessage?: string;
  confirmMessage?: string;
  rejectMessage?: string;
  statusId?: number;
  timesTbc?: boolean;
  attendeeCount?: number;
  waitlistCount?: number;
  confirmedCount?: number;
  checkedInCount?: number;
  isHidden?: boolean;
  myAttendeeStatus?: string;
  organizationId?: string;
};

export default Meet;
