import { OrganizationTheme } from "../types/themes";

export const ORGANIZATION_THEMES: OrganizationTheme[] = [
  {
    name: "Plain",
    canLight: true,
    canDark: true,
    canGlass: false,
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#F6F4EF",
    backgroundColorDark: "#0A1424",
  },
  {
    name: "Alpine",
    canLight: true,
    canDark: false,
    canGlass: false,
    backgroundLight: "background-alpine.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#f7f8fb",
    backgroundColorDark: "#0b1220",
  },
  {
    name: "Apocalypse",
    canLight: false,
    canDark: true,
    canGlass: false,
    backgroundDark: "background-apocalypse-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#f7f8fb",
    backgroundColorDark: "#0b1220",
  },
  {
    name: "Ballroom",
    canLight: true,
    canDark: true,
    canGlass: false,
    backgroundLight: "background-ballroom.png",
    backgroundDark: "background-ballroom-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#f7f8fb",
    backgroundColorDark: "#0b1220",
  },
  {
    name: "Forest",
    canLight: true,
    canDark: true,
    canGlass: false,
    backgroundLight: "background-forest.png",
    backgroundDark: "background-forest-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#eef5ef",
    backgroundColorDark: "#1e2e23",
  },
  {
    name: "Desert",
    canLight: true,
    canDark: true,
    canGlass: false,
    backgroundLight: "background-desert.png",
    backgroundDark: "background-desert-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#fdf6e3",
    backgroundColorDark: "#2e1e1e",
  },
  {
    name: "Diving",
    canLight: false,
    canDark: true,
    canGlass: false,
    backgroundDark: "background-diving-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#f7f8fb",
    backgroundColorDark: "#0b1220",
  },
  {
    name: "Ocean",
    canLight: true,
    canDark: true,
    canGlass: false,
    backgroundLight: "background-ocean.png",
    backgroundDark: "background-ocean-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#e6f0f6",
    backgroundColorDark: "#1b2730",
  },
  {
    name: "Original",
    canLight: true,
    canDark: true,
    canGlass: false,
    backgroundLight: "background-original.png",
    backgroundDark: "background-original-dark.png",
    logoLight: "adventuremeets-logo.svg",
    logoDark: "adventuremeets-logo-dark.svg",
    backgroundColorLight: "#f7f8fb",
    backgroundColorDark: "#0b1220",
  },
];

export const DEFAULT_ORGANIZATION_THEME = ORGANIZATION_THEMES[0];
