version: "3"
services:
  api:
    image: fringecoding/adventuremeets_api:${VERSION:-latest}
    env_file:
      - ./.env
    ports:
      - "3080:3030"
    networks:
      - adventuremeets
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == webapps1
  minio:
    image: minio/minio:latest
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - adventuremeets
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == webapps1

  backup_runner:
    image: fringecoding/adventuremeets_backup-runner:${VERSION:-latest}
    env_file:
      - ./.env
    environment:
      S3_BUCKET_NAME: fringecoding-backups/adventuremeets
      AWS_REGION: af-south-1
    networks:
      - adventuremeets

networks:
  adventuremeets:

volumes:
  minio_data:
